image: node:14

pipelines:
  default:
    - parallel:
      - step:
          name: Install Dependencies
          caches:
            - node
          script:
            - npm install
      - step:
          name: Lint Code
          script:
            - npm run lint
      - step:
          name: Build and Test
          caches:
            - node
          script:
            - npm install
            - npm run test -- --watch=false --browsers=ChromeHeadless
            - npm run build -- --prod
      - step:
          name: Security Scan
          script:
            # Example: Run a security scan for sensitive data.
            # You can use any security tool that suits your project.
            - pipe: atlassian/git-secrets-scan:0.5.1

definitions:
  caches:
    node: ~/.npm
